INC=/opt/cwp/include
LIK=/opt/cwp/lib
LIB=-lsu -lpar -lcwp -lm

#dot_refl::dot_refl.c
#	gcc dot_refl.c -o dot_diff  -I$(INC) -L$(LIK)  $(LIB)

dot_diff::dot_diff.c
	gcc dot_diff.c -g -o dot_diff -Wall -I$(INC) -L$(LIK)  $(LIB)


